### ISSUE TITLE
HLL UDFs not compatible with Spark 2.2+

### ISSUE THREAD

**Issue by AlexanderSaydakov** [apache/incubator-datasketches-hive#34]
This is to document an open issue, which appears to be a regression in Spark since version 2.2 with respect to support of Hive UDFs.
Discussion is here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sketches-user/GmH4-OlHP9g/MUay8NC5CQAJ

**Comment by AlexanderSaydakov** [comment]
We considered addressing the issue on our side, but decided not to do that.
https://github.com/DataSketches/sketches-hive/pull/33

**Comment by kgyrtkirk** [comment]
I think https://issues.apache.org/jira/browse/SPARK-24935 have addressed this issue

**Comment by AlexanderSaydakov** [comment]
Thank you. Let's close this.
